recipes:
  1:
    AI1_path: models\model_AI1.pt
    AI2_path: models\model_AI2.pt
    AI3_path: models\model_AI3.pt
  2:
    AI1_path: models\model_AI1.pt
    AI2_path: models\model_AI2.pt
    AI3_path: models\model_AI3.pt
  3:
    AI1_path: models\model_AI1.pt
    AI2_path: models\model_AI2.pt
    AI3_path: models\model_AI3.pt
  4:
    AI1_path: models\model_AI1.pt
    AI2_path: models\model_AI2.pt
    AI3_path: models\model_AI3.pt
  5:
    AI1_path: models\model_AI1.pt
    AI2_path: models\model_AI2.pt
    AI3_path: models\model_AI3.pt